# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ff8994c73dd12b5d3b06ead9ad8c90653032dd3bc129961326904d0420471199ceef3b9791a7ddaf64108ad84f1edb1afbad1af3b874e6208504279eddc04cb

test:
  secret_key_base: 93f6eea4afe48cea24594872fd4849f1110e65a125bd02e989e93f4ff2256cb45b770461ee1a4dd23110f295d2f2644e577836f111690318cbb98ac2e9c1a621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
